### ISSUE TITLE
Impossible to run the jar

### ISSUE THREAD

**Issue by xleyba** [addshore/facebook-data-image-exif#10]
I have tried to run the jar in my Macbook and refuse the work.
I have cloned the project and recompiled with the same result.

The error is 
`java -jar facebook-data-image-exif-0.10.jar
no main manifest attribute, in facebook-data-image-exif-0.10.jar`

Any clue?

**Comment by xleyba** [comment]
Also, if I try to run the binary I have downloaded from here, the error is:

`java -jar facebook-data-image-exif.jar
Error: Could not find or load main class com.github.addshore.facebook.data.image.exif.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application`

**Comment by addshore** [comment]
Looks like this is the same as https://github.com/addshore/facebook-data-image-exif/issues/6
