### ISSUE TITLE
Update website project

### ISSUE THREAD

**Issue by AlexQuiniou** [addshore/facebook-data-image-exif#11]
Hi

You could change https://addshore.com/2018/03/cambridge-analytics-deletefacebook-adding-exif-data-back/ by https://addshore.com/2019/02/add-exif-data-back-to-facebook-images-0-1/

![Screenshot_2020-01-24 addshore facebook-data-image-exif](https://user-images.githubusercontent.com/34091990/73055117-5889f080-3e8c-11ea-9ac4-154e8d1ffaea.png)

**Comment by addshore** [comment]
Thanks!
Done!
