### ISSUE TITLE
ERROR: the file does not exist in the expected location

### ISSUE THREAD

**Issue by maXity** [addshore/facebook-data-image-exif#16]
Unfortunately no luck with the tool for me - it seems as if Facebook might have changed the JSON file structure?

The log below suggests that the tool expects a local file path in the JSON files, but these files only contain fbcdn.net URLs:

![Logfile](https://user-images.githubusercontent.com/23332112/93017334-143c9380-f5c8-11ea-9dfd-3111e984a4d0.png)

Any clue how to fix this..?

**Comment by addshore** [comment]
Interesting.

In order to avoid downloading my whole facebook data again is there any chance you could check the examaple structure at https://github.com/addshore/facebook-data-image-exif/tree/master/facebook-example/photos_and_videos and see how it matches up with what you have downloaded?

basically the questions is, how do we get from this "interncache" URL that is now in the JSON, to the path on disk from the download?
if you can provide me with that I should be able to provide you with a fix :)

**Comment by maXity** [comment]
Sure, thank you for looking into that!

So before the structure looked like this:

`{
  "name": "Album 1 JSON",
  "photos": [
    {
      "uri": "photos_and_videos/second_album/a.jpg",
      "creation_timestamp": 1437454657,
      "media_metadata": {
        "photo_metadata": {
          "camera_make": "Huawei",
          "camera_model": "Nexus 6P",
          "modified_timestamp": 1510429759,
          "exposure": "166/10000",
          "focal_length": "4670/1000",
          "f_stop": "20000/10000",
          "iso_speed": 138,
          "latitude": 29.925027777778,
          "longitude": -90.088072222222,
          "orientation": 0,
          "original_width": 2412,
          "original_height": 0,
          "upload_ip": "167.161.108.51"
        }
      }
    },`

Whereas now it looks like this:

`{
  "name": "Ammersee 2013",
  "photos": [
    {
      "uri": "https://interncache-prn.fbcdn.net/v/t31.0-8/1273893_696176823726906_414900375_o.jpg?_nc_sid=73a6a0&efg=eyJ1cmxnZW4iOiJwaHBfdXJsZ2VuX2NsaWVudC9pbW9nZW46RFlJTWVkaWFVdGlscyJ9&_nc_ad=z-m&_nc_cid=0&_nc_ht=interncache-prn&oh=66732cac72a053ffb8c174e8c6b978d1&oe=5FA6CC32",
      "creation_timestamp": 1380621758,
      "media_metadata": {
        "photo_metadata": {
          "upload_ip": "132.187.102.41"
        }
      },
      "title": "Ammersee 2013",
      "description": "Die\u00c3\u009fen am Ammersee"
    }, `

One issue seems to be that the "uri" does not include a clear reference to the folder name any more ("Ammersee2013_5UvRab9PCw" in this case), and the file name is also only partially referenced (see above "1273893_696176823726906_414900375_o.jpg" but the full file name actually is "1273893_696176823726906_414900375_o_696176823726906.jpg").

Thank you for your help, and enjoy your coffee :)

**Comment by Snelmsy** [comment]
I am having this issue as well.

**Comment by neil-n-brown** [comment]
I am also having this issue.

**Comment by azzarri** [comment]
Same issue here. 

Path in json file referes to https:// path, and the error is that it can't find the file at "c:\slask\http:\interncache-prn.fb..."

    {
      "uri": "https://interncache-prn.fbcdn.net/v/t1.0-9/223505_10150168811888920_6733045_n.jpg?ccb=2&_nc_sid=73a6a0&efg=eyJ1cmxnZW4iOiJwaHBfdXJsZ2VuX2NsaWVudC9pbW9nZW46RFlJTWVkaWFVdGlscyJ9&_nc_ad=z-m&_nc_cid=0&_nc_ht=interncache-prn&oh=44135c86f4faed31bc7aa94dc54c2a31&oe=5FC776A8",
      "creation_timestamp": 1304663349,
      "media_metadata": {
        "photo_metadata": {
          "upload_ip": "84.17.195.206"
        }
      },

**Comment by OracleGe** [comment]
Same issue.

**Comment by royeboy06** [comment]
Same issue.

**Comment by dmjeffmoore** [comment]
@addshore I have written a fix for this bug and tried to push my branch but was failed due to permissions. Can I be added as a contributor to open a PR? Really nice work on this tool - so helpful.

**Comment by pdhixenbaugh** [comment]
I am also getting this. I also had to rename "posts" to "photos_and_videos" in the facebook data dump

**Comment by addshore** [comment]
Anyone coming here with this issue should find the fix in 0.12 now :)

This should be in 0.12 now https://github.com/addshore/facebook-data-image-exif/releases/tag/0.12

Thanks @loganrosen for the patch!!!
