### ISSUE TITLE
support for HTML download

### ISSUE THREAD

**Issue by bicepjai** [addshore/facebook-data-image-exif#20]
Downloaded the facebook data in HTML format long back. cannot find any tools for adding the meta data back. Do we have any options to support this data format ?

**Comment by addshore** [comment]
If your'e up for diving through history and some crappy code then yes.
This repo used to be written (all be it terribly) to work with various versions of the older HTML dumps.

There were a few different versions, so you success  might be hit or miss.

Try https://github.com/addshore/facebook-data-image-exif/tree/fced9a656204c18dbd87a5a31a9b2176dbce330a

Just after this commit the code in this repo was switched to JSON only dumps.

**Comment by bicepjai** [comment]
Thanks it did work. just make sure to point to the photos folder

**Comment by bicepjai** [comment]
I was wrong :) It did not work. the meta data did not get update

**Comment by addshore** [comment]
Been stale for over 6 months so closing
