### ISSUE TITLE
Job bulk after "Task is starting" log line

### ISSUE THREAD

**Issue by TomerBin** [addshore/facebook-data-image-exif#7]
![image](https://user-images.githubusercontent.com/13377822/62415822-8d815d00-b638-11e9-90e0-9925a93cbd7b.png)

**Comment by addshore** [comment]
What do you mean "Job bulk"?
Which version of the tool are you using?
What OS are you using?
What is the output if you run with debug mode / output on?

**Comment by AlexQuiniou** [comment]
I have the same problem.
You have `exiftool(-k).exe`
To resolve this remove `(-k)`
Like this `exiftool.exe`

**Comment by addshore** [comment]
Is this on Windows?

The intention was that this section of code would catch the case where people do not rename the exe to just be "exiftool.exe".

https://github.com/addshore/facebook-data-image-exif/blob/03846a5bbb47b5bd625de6217723a33403ebbadf/src/com/github/addshore/facebook/data/image/exif/Main.java#L204-L208

**Comment by AlexQuiniou** [comment]
Yep Windows 10
Got from the official website

> The stand-alone Windows executable does not require Perl. Just download and un-zip the archive then double-click on "exiftool(-k).exe" to read the application documentation, drag-and-drop files and folders to view meta information, or rename to "exiftool.exe" for command-line use. Runs on all versions of Windows.

**Comment by addshore** [comment]
Interesting, as far as I can see the code should catch cases like this.
Could you provide a screenshot of the input fields before you start the process?
Or turning on debug output might output them once you click start.

I'll leave this ticket open until I can get this fixed when i'm back from traveling.

**Comment by addshore** [comment]
Should be improved when I release the next version (0.10)

**Comment by addshore** [comment]
https://github.com/addshore/facebook-data-image-exif/releases/tag/0.10
