### ISSUE TITLE
Use the creation_timestamp

### ISSUE THREAD

**Issue by AlexQuiniou** [addshore/facebook-data-image-exif#8]
### Version of the tool

> 0.9

### Version Exiftool

> 11.61

### OS

> Windows 10

### Parameter archive

> Format JSON
> Média en haute qualité

### What gone wrong
Everything goes as espected but ...
here you have metadata for a recent picture

>     {
>       "uri": "photos_and_videos/Telechargementsmobiles_WR5m5ZjuZg/67527762_10211331010189674_6207711348978089984_o_10211331010149673.jpg",
>       "creation_timestamp": 1565014981,
>       "media_metadata": {
>         "photo_metadata": {
>           "camera_make": "Sony",
>           "camera_model": "G8441",
>           "taken_timestamp": 1565014901,
>           "modified_timestamp": 1565014901,
>           "exposure": "10/3200",
>           "focal_length": "196/100",
>           "f_stop": "24/10",
>           "iso_speed": 40,
>           "orientation": 8,
>           "upload_ip": "-"
>         }
>       },
>       "title": "T\u00c3\u00a9l\u00c3\u00a9chargements mobiles",
>       "description": "Voir loin depuis son nid"
>     }

and there for an old picture

>     {
>       "uri": "photos_and_videos/Telechargementsmobiles_WR5m5ZjuZg/36775546_10209274208690922_2334065595797995520_o_10209274208610920.jpg",
>       "creation_timestamp": 1531058594,
>       "media_metadata": {
>         "photo_metadata": {
>           "upload_ip": "-"
>         }
>       },
>       "title": "T\u00c3\u00a9l\u00c3\u00a9chargements mobiles"
>     },

Can I get the `creation_timestamp` used in this case ?

**Comment by addshore** [comment]
So the in the current code, the creation_timestamp in that position would only be checked if the media_metadata key did not exist.

If condition is:
https://github.com/addshore/facebook-data-image-exif/blob/03846a5bbb47b5bd625de6217723a33403ebbadf/src/com/github/addshore/facebook/data/image/exif/ProcessingTask.java#L205-L214

Else is:
https://github.com/addshore/facebook-data-image-exif/blob/03846a5bbb47b5bd625de6217723a33403ebbadf/src/com/github/addshore/facebook/data/image/exif/ProcessingTask.java#L205-L214

Looks like the logic here needs to be poked around a bit to fallback to the higher level creation timestamp if no timestamps appear in the media or photo meta data?

Perhaps things like this should start having options as well with some sensible defaults, as I imagine some users might not want to do this.

I won't be able to work on this for a couple of months as I am currently traveling.

**Comment by thatcow** [comment]
I've got this same issue. The process works but nothing is written to EXIF as only creation_timestamp has a value. As explained above.

Would be great if you could resolve that!

**Comment by sergiowalls** [comment]
A python workaround to create _taken_timestamp_ from _creation_timestamp_ :

```python
import json

path = 'path\to\album\folder'
number_of_json_files = X + 1

for i in range(0, number_of_json_files):
    filename = '{0}.json'.format(str(i))
    with open(path + filename, 'r') as json_file:
        data = json.load(json_file)
        for photo in data['photos']:
            if 'media_metadata' in photo and 'photo_metadata' in photo['media_metadata'] and 'taken_timestamp' in \
                    photo['media_metadata'][
                        'photo_metadata']:
                pass
            else:
                try:
                    if 'media_metadata' not in photo:
                        photo['media_metadata'] = {'photo_metadata': {'taken_timestamp': ''}}
                    photo['media_metadata']['photo_metadata']['taken_timestamp'] = photo['creation_timestamp']
                except KeyError as e:
                    print(i, e)
                    print(photo)
        json_file.close()

    with open(path + filename, 'w') as json_file:
        json.dump(data, json_file)
        json_file.close()

```

It should be run before running the jar. Notice that the JSON files will be overridden.

**Comment by addshore** [comment]
Will be fixed in the next release that is 0.10 :)

**Comment by zgosalvez** [comment]
Glad to have you updating this again @addshore.

**Comment by addshore** [comment]
https://github.com/addshore/facebook-data-image-exif/releases/tag/0.10

**Comment by AlexQuiniou** [comment]
Thanks
I have use it for archiving my pics
😃

**Comment by addshore** [comment]
If you have any other feature requests of suggested UI changes please let me know / file issues.
I'd love to make it as easy as possible for people to use, and I currently have the project loaded into my brain again currently!
